### ISSUE TITLE
Local Python environment used as shebang in pyz

### ISSUE THREAD

**Issue by lofidevops** [frostming/pdm-packer#34]
**Describe the bug**

The shebang in my pyz file points to the build-time project venv. This won't exist on target environments.

**To reproduce**

1. Create local environment with `pdm sync --dev`
2. Build pyz file with `pdm pack`
3. Open pyz file in a text editor and inspect first line

**Expected behavior**

[To the best of my knowledge,](https://realpython.com/python-shebang/#how-can-you-define-a-portable-shebang) the universal shebang for Python 3 is:

```
#!/usr/bin/env python3
```

Instead I see:

```
#!/home/user/Documents/myproject/.venv/bin/python
```

**System**

```
$ pipx list --include-injected
...
   package pdm 2.5.2, installed using Python 3.10.4
    - pdm
    Injected Packages:
      - keyring 23.9.3
      - pdm-packer 0.6.0
```

```
$ lsb_release --all
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

**Comment by lofidevops** [comment]
Replicated with `pdm pack --exe`

In this case, deleting the `.venv` folder means you can no longer invoke `./myproject`. Running `python3 myproject` still works.

In the former case (`pdm pack`), you are expected to run `python3 myproject.pyz` and this continues to work after deleting the `.venv` folder.

**Comment by frostming** [comment]
The generated zipapp should only work with the same Python version as generated, therefore, using a generic `/usr/bin/env python` is a bad idea because you don't know which version it points to. You can however specify the python in the shebang line with the `-i/--interperter` option, if you know what you are doing.

We have already offered enough flexibility and I don't believe this a bug of any kind. Closing it now.

**Comment by lofidevops** [comment]
@frostming I overlooked the `--interpreter` option. That solves my problem perfectly, thank you!
